### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by elisar4** [elisar4/nodes#16]
- [ ] add nice readme file
- [ ] add `Logic` module documentation
- [ ] remove nodes logic concept (outdated)
